const linkedIn = "https://www.linkedin.com/in/ivan-lukovskii-2a5141244/"
const gitHub = "https://github.com/toprogramm"
const email = "onelukovskii@gmail.com"
const website = "https://lukovskii.com"
const telegram = "@toprogramm"