export const linkedIn = "https://www.linkedin.com/in/ivan-lukovskii-2a5141244/"
export const gitHub = "https://github.com/toprogramm"
export const email = "onelukovskii@gmail.com"
export const website = "https://lukovskii.com"
export const telegram = "@toprogramm"